CREATE TABLE person (
    id serial PRIMARY KEY, "name" varchar NOT NULL, age int CHECK (age > 0), email varchar UNIQUE
);
--    id int generated by default as identity primary key,

INSERT INTO person (name, age, email)
VALUES
    ('John', 20, 'john@gmail.com'),('Jane', 21, 'jane@gmail.com'),('Jack', 22, 'jack@gmail.com'),('Jill', 23, 'jill@gmail.com'),('Jim', 24, 'jim@gmail.com')

SELECT *
FROM person

DROP TABLE person

CREATE SEQUENCE first_sequence

SELECT nextval('first_sequence')

DROP SEQUENCE first_sequence

COMMIT
